// Tailwind CSS theme extension -- paste into tailwind.config.js > theme.extend
module.exports = {
  theme: {
    extend: {
      colors: {
        'primary': '#4a7c53',
        'on-primary': '#ffffff',
        'primary-container': '#e1e9e2',
        'on-primary-container': '#151d17',
        'primary-fixed': '#e1e9e2',
        'primary-fixed-dim': '#bfd8c3',
        'on-primary-fixed': '#151d17',
        'on-primary-fixed-variant': '#395f40',
        'secondary': '#4a7c6f',
        'on-secondary': '#ffffff',
        'secondary-container': '#e1e9e7',
        'on-secondary-container': '#151d1b',
        'tertiary': '#495b7d',
        'on-tertiary': '#fffffe',
        'tertiary-container': '#e0e4ea',
        'on-tertiary-container': '#15181d',
        'error': '#863f16',
        'on-error': '#feffff',
        'error-container': '#f2e2d8',
        'on-error-container': '#24160e',
        'surface': '#C8DDD0',
        'on-surface': '#2C522F',
        'surface-variant': '#deece0',
        'on-surface-variant': '#5A7860',
        'surface-container-lowest': '#e3e8d8',
        'surface-container-low': '#dde6d4',
        'surface-container': '#d6e4d1',
        'surface-container-high': '#cfe1ce',
        'surface-container-highest': '#cbdfce',
        'outline': '#8AAA80',
        'outline-variant': '#bddac2',
        'inverse-surface': '#244129',
        'inverse-on-surface': '#f0f4f1',
        'inverse-primary': '#bfd8c3',
        'scrim': '#000000',
        'shadow': '#000000',
        'wheat-chartreuse': '#6e842b',
        'on-wheat-chartreuse': '#ffffff',
        'wheat-chartreuse-container': '#e9eedc',
        'on-wheat-chartreuse-container': '#1d2111',
      },
    },
  },
};