// Tailwind CSS theme extension — paste into tailwind.config.js > theme.extend
module.exports = {
  theme: {
    extend: {
      colors: {
        'primary': '#48557d',
        'on-primary': '#ffffff',
        'primary-container': '#e0e3ea',
        'on-primary-container': '#15171d',
        'primary-fixed': '#e0e3ea',
        'primary-fixed-dim': '#bec5d9',
        'on-primary-fixed': '#15171d',
        'on-primary-fixed-variant': '#374261',
        'secondary': '#587358',
        'on-secondary': '#fffeff',
        'secondary-container': '#e3e7e3',
        'on-secondary-container': '#171b17',
        'tertiary': '#705477',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#e7e2e8',
        'on-tertiary-container': '#1b161c',
        'error': '#861636',
        'on-error': '#feffff',
        'error-container': '#f2d8e0',
        'on-error-container': '#240e14',
        'surface': '#f9f9fa',
        'on-surface': '#16181c',
        'surface-variant': '#e0e3ea',
        'on-surface-variant': '#3e455a',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f4f5',
        'surface-container': '#eeeef1',
        'surface-container-high': '#e8e9ec',
        'surface-container-highest': '#e2e4e8',
        'outline': '#687496',
        'outline-variant': '#c2c7d5',
        'inverse-surface': '#2d3038',
        'inverse-on-surface': '#f1f1f2',
        'inverse-primary': '#bec5d9',
        'scrim': '#000000',
        'shadow': '#000000',
      },
    },
  },
};