// Tailwind CSS theme extension — paste into tailwind.config.js > theme.extend
module.exports = {
  theme: {
    extend: {
      colors: {
        'primary': '#862619',
        'on-primary': '#ffffff',
        'primary-container': '#f1dcd9',
        'on-primary-container': '#23110f',
        'primary-fixed': '#f1dcd9',
        'primary-fixed-dim': '#eeb1a9',
        'on-primary-fixed': '#23110f',
        'on-primary-fixed-variant': '#802418',
        'secondary': '#3d8054',
        'on-secondary': '#fffeff',
        'secondary-container': '#dfebe3',
        'on-secondary-container': '#141e17',
        'tertiary': '#3b4d80',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#dee2ec',
        'on-tertiary-container': '#13161f',
        'error': '#861d16',
        'on-error': '#feffff',
        'error-container': '#f2dad8',
        'on-error-container': '#240f0e',
        'surface': '#faf9f9',
        'on-surface': '#1c1716',
        'surface-variant': '#eae1e0',
        'on-surface-variant': '#5a413e',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f4f4',
        'surface-container': '#f1eeee',
        'surface-container-high': '#ece9e8',
        'surface-container-highest': '#e8e3e2',
        'outline': '#966d68',
        'outline-variant': '#d5c4c2',
        'inverse-surface': '#382f2d',
        'inverse-on-surface': '#f2f1f1',
        'inverse-primary': '#eeb1a9',
        'scrim': '#000000',
        'shadow': '#000000',
      },
    },
  },
};