// Tailwind CSS theme extension — paste into tailwind.config.js > theme.extend
module.exports = {
  theme: {
    extend: {
      colors: {
        'primary': '#418233',
        'on-primary': '#ffffff',
        'primary-container': '#e0eddd',
        'on-primary-container': '#152012',
        'primary-fixed': '#e0eddd',
        'primary-fixed-dim': '#bde2b5',
        'on-primary-fixed': '#152012',
        'on-primary-fixed-variant': '#376e2a',
        'secondary': '#44647e',
        'on-secondary': '#ffffff',
        'secondary-container': '#e0e5ea',
        'on-secondary-container': '#14191e',
        'tertiary': '#818139',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#ececde',
        'on-tertiary-container': '#1f1f13',
        'error': '#863916',
        'on-error': '#feffff',
        'error-container': '#f2e0d8',
        'on-error-container': '#24150e',
        'surface': '#f9faf9',
        'on-surface': '#171c16',
        'surface-variant': '#e2eae0',
        'on-surface-variant': '#435a3e',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f5f4',
        'surface-container': '#eef1ee',
        'surface-container-high': '#e9ece8',
        'surface-container-highest': '#e3e8e2',
        'outline': '#709668',
        'outline-variant': '#c6d5c2',
        'inverse-surface': '#2f382d',
        'inverse-on-surface': '#f1f2f1',
        'inverse-primary': '#bde2b5',
        'scrim': '#000000',
        'shadow': '#000000',
      },
    },
  },
};