// Tailwind CSS theme extension -- paste into tailwind.config.js > theme.extend
module.exports = {
  theme: {
    extend: {
      colors: {
        'primary': '#2e8383',
        'on-primary': '#fffefe',
        'primary-container': '#dceeee',
        'on-primary-container': '#122020',
        'primary-fixed': '#dceeee',
        'primary-fixed-dim': '#b3e4e4',
        'on-primary-fixed': '#122020',
        'on-primary-fixed-variant': '#277171',
        'secondary': '#862e1f',
        'on-secondary': '#ffffff',
        'secondary-container': '#f0ddda',
        'on-secondary-container': '#23120f',
        'tertiary': '#857026',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#efebdb',
        'on-tertiary-container': '#211e11',
        'error': '#864d16',
        'on-error': '#feffff',
        'error-container': '#f2e5d8',
        'on-error-container': '#24190e',
        'surface': '#D8C880',
        'on-surface': '#2C5252',
        'surface-variant': '#deecec',
        'on-surface-variant': '#5A6A5A',
        'surface-container-lowest': '#e6daa0',
        'surface-container-low': '#e4d799',
        'surface-container': '#e1d392',
        'surface-container-high': '#decf8c',
        'surface-container-highest': '#dbcb86',
        'outline': '#8A9A80',
        'outline-variant': '#bddada',
        'inverse-surface': '#244141',
        'inverse-on-surface': '#f0f4f4',
        'inverse-primary': '#b3e4e4',
        'scrim': '#000000',
        'shadow': '#000000',
        'counter-mahogany': '#834531',
        'on-counter-mahogany': '#ffffff',
        'counter-mahogany-container': '#ede1dd',
        'on-counter-mahogany-container': '#201512',
        'neon-green': '#2c8451',
        'on-neon-green': '#ffffff',
        'neon-green-container': '#dceee4',
        'on-neon-green-container': '#112118',
      },
    },
  },
};