// Tailwind CSS theme extension — paste into tailwind.config.js > theme.extend
module.exports = {
  theme: {
    extend: {
      colors: {
        'primary': '#368273',
        'on-primary': '#fffefe',
        'primary-container': '#deece9',
        'on-primary-container': '#131f1d',
        'primary-fixed': '#deece9',
        'primary-fixed-dim': '#b7e0d8',
        'on-primary-fixed': '#131f1d',
        'on-primary-fixed-variant': '#2d6b5f',
        'secondary': '#827034',
        'on-secondary': '#ffffff',
        'secondary-container': '#ede9dd',
        'on-secondary-container': '#1f1c13',
        'tertiary': '#845b2d',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#eee6dc',
        'on-tertiary-container': '#201912',
        'error': '#864a16',
        'on-error': '#feffff',
        'error-container': '#f2e4d8',
        'on-error-container': '#24180e',
        'surface': '#f9fafa',
        'on-surface': '#161c1b',
        'surface-variant': '#e0eae8',
        'on-surface-variant': '#3e5a54',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f5f5',
        'surface-container': '#eef1f0',
        'surface-container-high': '#e8eceb',
        'surface-container-highest': '#e2e8e7',
        'outline': '#68968d',
        'outline-variant': '#c2d5d1',
        'inverse-surface': '#2d3836',
        'inverse-on-surface': '#f1f2f2',
        'inverse-primary': '#b7e0d8',
        'scrim': '#000000',
        'shadow': '#000000',
      },
    },
  },
};