// Tailwind CSS theme extension -- paste into tailwind.config.js > theme.extend
module.exports = {
  theme: {
    extend: {
      colors: {
        'primary': '#204985',
        'on-primary': '#ffffff',
        'primary-container': '#dae3f0',
        'on-primary-container': '#101722',
        'primary-fixed': '#dae3f0',
        'primary-fixed-dim': '#adc5ea',
        'on-primary-fixed': '#101722',
        'on-primary-fixed-variant': '#1e437a',
        'secondary': '#366382',
        'on-secondary': '#fffefe',
        'secondary-container': '#dee6ec',
        'on-secondary-container': '#131a1f',
        'tertiary': '#826b35',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#ede8dd',
        'on-tertiary-container': '#1f1c13',
        'error': '#861639',
        'on-error': '#feffff',
        'error-container': '#f2d8e0',
        'on-error-container': '#240e15',
        'surface': '#D8CDB0',
        'on-surface': '#2C3952',
        'surface-variant': '#dee4ec',
        'on-surface-variant': '#7A7060',
        'surface-container-lowest': '#e7e0cc',
        'surface-container-low': '#e4dcc6',
        'surface-container': '#e1d8c0',
        'surface-container-high': '#ded4bb',
        'surface-container-highest': '#dbd0b5',
        'outline': '#A8A088',
        'outline-variant': '#bdc9da',
        'inverse-surface': '#243041',
        'inverse-on-surface': '#f0f1f4',
        'inverse-primary': '#adc5ea',
        'scrim': '#000000',
        'shadow': '#000000',
        'foam-white': '#757556',
        'on-foam-white': '#ffffff',
        'foam-white-container': '#e8e8e2',
        'on-foam-white-container': '#1b1b17',
      },
    },
  },
};