// Tailwind CSS theme extension -- paste into tailwind.config.js > theme.extend
module.exports = {
  theme: {
    extend: {
      colors: {
        'primary': '#86281a',
        'on-primary': '#ffffff',
        'primary-container': '#f1dcd9',
        'on-primary-container': '#23110f',
        'primary-fixed': '#f1dcd9',
        'primary-fixed-dim': '#eeb2aa',
        'on-primary-fixed': '#23110f',
        'on-primary-fixed-variant': '#7f2619',
        'secondary': '#338247',
        'on-secondary': '#ffffff',
        'secondary-container': '#ddede1',
        'on-secondary-container': '#122016',
        'tertiary': '#855e26',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#efe7db',
        'on-tertiary-container': '#211a11',
        'error': '#861d16',
        'on-error': '#feffff',
        'error-container': '#f2dad8',
        'on-error-container': '#240f0e',
        'surface': '#B84030',
        'on-surface': '#F2E7E2',
        'surface-variant': '#eedfdc',
        'on-surface-variant': '#E8C0B0',
        'surface-container-lowest': '#d6a797',
        'surface-container-low': '#d19482',
        'surface-container': '#cd7e6b',
        'surface-container-high': '#ca6853',
        'surface-container-highest': '#c74f3b',
        'outline': '#984030',
        'outline-variant': '#e7b7b0',
        'inverse-surface': '#531a12',
        'inverse-on-surface': '#e9c3bd',
        'inverse-primary': '#eeb2aa',
        'scrim': '#000000',
        'shadow': '#000000',
        'hot-pink': '#852254',
        'on-hot-pink': '#ffffff',
        'hot-pink-container': '#f0dae5',
        'on-hot-pink-container': '#221019',
        'plate-blue': '#385081',
        'on-plate-blue': '#ffffff',
        'plate-blue-container': '#dee3ec',
        'on-plate-blue-container': '#13171f',
      },
    },
  },
};