// Tailwind CSS theme extension -- paste into tailwind.config.js > theme.extend
module.exports = {
  theme: {
    extend: {
      colors: {
        'primary': '#284684',
        'on-primary': '#ffffff',
        'primary-container': '#dce2ee',
        'on-primary-container': '#111621',
        'primary-fixed': '#dce2ee',
        'primary-fixed-dim': '#b0c2e7',
        'on-primary-fixed': '#111621',
        'on-primary-fixed-variant': '#233d75',
        'secondary': '#4a7c4f',
        'on-secondary': '#ffffff',
        'secondary-container': '#e1e9e1',
        'on-secondary-container': '#151d16',
        'tertiary': '#61457e',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#e5e0ea',
        'on-tertiary-container': '#19151d',
        'error': '#861638',
        'on-error': '#feffff',
        'error-container': '#f2d8e0',
        'on-error-container': '#240e15',
        'surface': '#D4B832',
        'on-surface': '#2C3952',
        'surface-variant': '#dee2ec',
        'on-surface-variant': '#8A7518',
        'surface-container-lowest': '#f0e4a0',
        'surface-container-low': '#ebdc89',
        'surface-container': '#e6d372',
        'surface-container-high': '#e0ca5c',
        'surface-container-highest': '#dac147',
        'outline': '#B89820',
        'outline-variant': '#bdc6da',
        'inverse-surface': '#252e40',
        'inverse-on-surface': '#f0f1f3',
        'inverse-primary': '#b0c2e7',
        'scrim': '#000000',
        'shadow': '#000000',
        'petal-highlight': '#2a4d84',
        'on-petal-highlight': '#fffffe',
        'petal-highlight-container': '#dce3ee',
        'on-petal-highlight-container': '#111721',
        'vase-ochre': '#855b27',
        'on-vase-ochre': '#ffffff',
        'vase-ochre-container': '#efe6db',
        'on-vase-ochre-container': '#211a11',
      },
    },
  },
};