// Tailwind CSS theme extension -- paste into tailwind.config.js > theme.extend
module.exports = {
  theme: {
    extend: {
      colors: {
        'primary': '#49567d',
        'on-primary': '#ffffff',
        'primary-container': '#e0e3ea',
        'on-primary-container': '#15171d',
        'primary-fixed': '#e0e3ea',
        'primary-fixed-dim': '#bec5d9',
        'on-primary-fixed': '#15171d',
        'on-primary-fixed-variant': '#384260',
        'secondary': '#567556',
        'on-secondary': '#ffffff',
        'secondary-container': '#e2e8e2',
        'on-secondary-container': '#171b17',
        'tertiary': '#67517a',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#e5e1e9',
        'on-tertiary-container': '#19161c',
        'error': '#861636',
        'on-error': '#feffff',
        'error-container': '#f2d8e0',
        'on-error-container': '#240e14',
        'surface': '#C8D0D8',
        'on-surface': '#2C3652',
        'surface-variant': '#dee1ec',
        'on-surface-variant': '#545865',
        'surface-container-lowest': '#dee2e8',
        'surface-container-low': '#dadfe4',
        'surface-container': '#d5dbe1',
        'surface-container-high': '#d1d7de',
        'surface-container-highest': '#ccd3db',
        'outline': '#9AA0B0',
        'outline-variant': '#bdc4da',
        'inverse-surface': '#252c40',
        'inverse-on-surface': '#f0f1f3',
        'inverse-primary': '#bec5d9',
        'scrim': '#000000',
        'shadow': '#000000',
        'lily-peach': '#835a30',
        'on-lily-peach': '#ffffff',
        'lily-peach-container': '#ede5dd',
        'on-lily-peach-container': '#201912',
        'cloud-cream': '#826536',
        'on-cloud-cream': '#ffffff',
        'cloud-cream-container': '#ece7de',
        'on-cloud-cream-container': '#1f1b13',
      },
    },
  },
};