// Tailwind CSS theme extension — paste into tailwind.config.js > theme.extend
module.exports = {
  theme: {
    extend: {
      colors: {
        'primary': '#294e84',
        'on-primary': '#ffffff',
        'primary-container': '#dce3ee',
        'on-primary-container': '#111721',
        'primary-fixed': '#dce3ee',
        'primary-fixed-dim': '#b1c6e6',
        'on-primary-fixed': '#111721',
        'on-primary-fixed-variant': '#244474',
        'secondary': '#84692d',
        'on-secondary': '#ffffff',
        'secondary-container': '#eee8dc',
        'on-secondary-container': '#201c12',
        'tertiary': '#597265',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#e3e7e5',
        'on-tertiary-container': '#171b19',
        'error': '#861639',
        'on-error': '#feffff',
        'error-container': '#f2d8e0',
        'on-error-container': '#240e15',
        'surface': '#f9f9fa',
        'on-surface': '#16191c',
        'surface-variant': '#e0e4ea',
        'on-surface-variant': '#3e495a',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f4f5',
        'surface-container': '#eeeff1',
        'surface-container-high': '#e8eaec',
        'surface-container-highest': '#e2e5e8',
        'outline': '#687b96',
        'outline-variant': '#c2cad5',
        'inverse-surface': '#2d3238',
        'inverse-on-surface': '#f1f2f2',
        'inverse-primary': '#b1c6e6',
        'scrim': '#000000',
        'shadow': '#000000',
      },
    },
  },
};