// Tailwind CSS theme extension — paste into tailwind.config.js > theme.extend
module.exports = {
  theme: {
    extend: {
      colors: {
        'primary': '#374481',
        'on-primary': '#ffffff',
        'primary-container': '#dee0ec',
        'on-primary-container': '#13151f',
        'primary-fixed': '#dee0ec',
        'primary-fixed-dim': '#b7bee0',
        'on-primary-fixed': '#13151f',
        'on-primary-fixed-variant': '#2d386b',
        'secondary': '#86701a',
        'on-secondary': '#ffffff',
        'secondary-container': '#f1ecd9',
        'on-secondary-container': '#231f0f',
        'tertiary': '#457e43',
        'on-tertiary': '#fffeff',
        'tertiary-container': '#e0eae0',
        'on-tertiary-container': '#151e14',
        'error': '#861635',
        'on-error': '#feffff',
        'error-container': '#f2d8df',
        'on-error-container': '#240e14',
        'surface': '#f9f9fa',
        'on-surface': '#16171c',
        'surface-variant': '#e0e2ea',
        'on-surface-variant': '#3e435a',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f4f5',
        'surface-container': '#eeeef1',
        'surface-container-high': '#e8e9ec',
        'surface-container-highest': '#e2e3e8',
        'outline': '#687096',
        'outline-variant': '#c2c5d5',
        'inverse-surface': '#2d2f38',
        'inverse-on-surface': '#f1f1f2',
        'inverse-primary': '#b7bee0',
        'scrim': '#000000',
        'shadow': '#000000',
      },
    },
  },
};