// Tailwind CSS theme extension — paste into tailwind.config.js > theme.extend
module.exports = {
  theme: {
    extend: {
      colors: {
        'primary': '#338273',
        'on-primary': '#ffffff',
        'primary-container': '#ddedea',
        'on-primary-container': '#12201d',
        'primary-fixed': '#ddedea',
        'primary-fixed-dim': '#b5e2d9',
        'on-primary-fixed': '#12201d',
        'on-primary-fixed-variant': '#2b6d60',
        'secondary': '#856926',
        'on-secondary': '#ffffff',
        'secondary-container': '#efe9db',
        'on-secondary-container': '#211c11',
        'tertiary': '#853527',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#efdedb',
        'on-tertiary-container': '#211311',
        'error': '#864a16',
        'on-error': '#feffff',
        'error-container': '#f2e4d8',
        'on-error-container': '#24180e',
        'surface': '#f9fafa',
        'on-surface': '#161c1b',
        'surface-variant': '#e0eae8',
        'on-surface-variant': '#3e5a54',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f5f5',
        'surface-container': '#eef1f0',
        'surface-container-high': '#e8eceb',
        'surface-container-highest': '#e2e8e7',
        'outline': '#68968d',
        'outline-variant': '#c2d5d1',
        'inverse-surface': '#2d3836',
        'inverse-on-surface': '#f1f2f2',
        'inverse-primary': '#b5e2d9',
        'scrim': '#000000',
        'shadow': '#000000',
      },
    },
  },
};