// Tailwind CSS theme extension -- paste into tailwind.config.js > theme.extend
module.exports = {
  theme: {
    extend: {
      colors: {
        'primary': '#368273',
        'on-primary': '#fffefe',
        'primary-container': '#deece9',
        'on-primary-container': '#131f1d',
        'primary-fixed': '#deece9',
        'primary-fixed-dim': '#b7e0d8',
        'on-primary-fixed': '#131f1d',
        'on-primary-fixed-variant': '#2d6b5f',
        'secondary': '#827034',
        'on-secondary': '#ffffff',
        'secondary-container': '#ede9dd',
        'on-secondary-container': '#1f1c13',
        'tertiary': '#845b2d',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#eee6dc',
        'on-tertiary-container': '#201912',
        'error': '#864a16',
        'on-error': '#feffff',
        'error-container': '#f2e4d8',
        'on-error-container': '#24180e',
        'surface': '#C8C0A0',
        'on-surface': '#2A3830',
        'surface-variant': '#deece9',
        'on-surface-variant': '#5A6858',
        'surface-container-lowest': '#e0dcc7',
        'surface-container-low': '#dbd6bf',
        'surface-container': '#d6d0b7',
        'surface-container-high': '#d1cbaf',
        'surface-container-highest': '#ccc5a7',
        'outline': '#8A9A80',
        'outline-variant': '#bddad4',
        'inverse-surface': '#25403b',
        'inverse-on-surface': '#f0f3f3',
        'inverse-primary': '#b7e0d8',
        'scrim': '#000000',
        'shadow': '#000000',
        'pale-jade': '#3f7f64',
        'on-pale-jade': '#ffffff',
        'pale-jade-container': '#dfebe6',
        'on-pale-jade-container': '#141e1a',
        'dark-umber': '#816238',
        'on-dark-umber': '#ffffff',
        'dark-umber-container': '#ece6de',
        'on-dark-umber-container': '#1f1a13',
        'mist-white': '#747457',
        'on-mist-white': '#ffffff',
        'mist-white-container': '#e8e8e2',
        'on-mist-white-container': '#1b1b17',
      },
    },
  },
};