// Tailwind CSS theme extension — paste into tailwind.config.js > theme.extend
module.exports = {
  theme: {
    extend: {
      colors: {
        'primary': '#4d7e3b',
        'on-primary': '#ffffff',
        'primary-container': '#e2ebdf',
        'on-primary-container': '#171f13',
        'primary-fixed': '#e2ebdf',
        'primary-fixed-dim': '#c3deb9',
        'on-primary-fixed': '#171f13',
        'on-primary-fixed-variant': '#406830',
        'secondary': '#425d7f',
        'on-secondary': '#ffffff',
        'secondary-container': '#dfe4eb',
        'on-secondary-container': '#14181e',
        'tertiary': '#846d28',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#efeadb',
        'on-tertiary-container': '#211d11',
        'error': '#863816',
        'on-error': '#feffff',
        'error-container': '#f2e0d8',
        'on-error-container': '#24150e',
        'surface': '#f9faf9',
        'on-surface': '#181c16',
        'surface-variant': '#e3eae0',
        'on-surface-variant': '#465a3e',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f5f4',
        'surface-container': '#eff1ee',
        'surface-container-high': '#e9ece8',
        'surface-container-highest': '#e4e8e2',
        'outline': '#759668',
        'outline-variant': '#c7d5c2',
        'inverse-surface': '#30382d',
        'inverse-on-surface': '#f1f2f1',
        'inverse-primary': '#c3deb9',
        'scrim': '#000000',
        'shadow': '#000000',
      },
    },
  },
};