// Tailwind CSS theme extension -- paste into tailwind.config.js > theme.extend
module.exports = {
  theme: {
    extend: {
      colors: {
        'primary': '#3d5880',
        'on-primary': '#fffffe',
        'primary-container': '#dfe4eb',
        'on-primary-container': '#14181e',
        'primary-fixed': '#dfe4eb',
        'primary-fixed-dim': '#bac8dd',
        'on-primary-fixed': '#14181e',
        'on-primary-fixed-variant': '#314767',
        'secondary': '#457e43',
        'on-secondary': '#ffffff',
        'secondary-container': '#e0ebdf',
        'on-secondary-container': '#151e14',
        'tertiary': '#856025',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#efe7db',
        'on-tertiary-container': '#221b10',
        'error': '#861639',
        'on-error': '#feffff',
        'error-container': '#f2d8e0',
        'on-error-container': '#240e15',
        'surface': '#C8D0D8',
        'on-surface': '#2C3A52',
        'surface-variant': '#dee4ec',
        'on-surface-variant': '#6A7068',
        'surface-container-lowest': '#e0ddd0',
        'surface-container-low': '#d8dece',
        'surface-container': '#cedccc',
        'surface-container-high': '#cbdbd1',
        'surface-container-highest': '#c9d9d9',
        'outline': '#98A098',
        'outline-variant': '#bec9d9',
        'inverse-surface': '#253040',
        'inverse-on-surface': '#f0f1f3',
        'inverse-primary': '#bac8dd',
        'scrim': '#000000',
        'shadow': '#000000',
      },
    },
  },
};